Hw02 express
Natali2721/nodejs-homework-rest-api pull request #1
Opened 2023-01-21 16:20 UTC by Natali2721

вітаю, спершу створила реквест у репозиторій goit, потім побачила, що я не перша :) 
прошу перевірити мій витвір. дякую

2023-01-21 19:52 UTC, Eastvarga requested changes
Є Зауваження

2023-01-21 19:52 UTC, Eastvarga commented on models/contacts.js
> +  return JSON.parse(data);
краще виділити ці дії
const data = await fs.readFile(contactsPath, "utf8");
  return JSON.parse(data);
  у окрему функцію - getContacts() наприклад, та перевикористовувати її а не дублювати строки коду

2023-01-21 19:52 UTC, Eastvarga commented on models/contacts.js
> +  if (dataAfterRemove.length === parsedData.length) {
щоб повертати видалений об'єкт краще додати неініціалізовану змінну до фільтрації а у методі фільтраціїї ініціалізувати її  об'єктом при співпадінні item.id === contactId
тоді якщо ця змінна не пуста можна повертати її значення, як результат видалення, а відфільтрований масив зберігати, а якщо ні повертати помилку.

2023-01-21 19:52 UTC, Eastvarga commented on models/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(dataAfterRemove));
це також можна виділити в окрему функцію - writeToDb(contacts) - наприклад

2023-01-21 19:52 UTC, Eastvarga commented on models/contacts.js
> +    return false;
Поведінка функцій дій з контактами повинна бути логічною для одного рівня дій - взяти, створити, видалити - повертає елемент або набір елементів - а у вас логіка порушена - чомусь видалення повертає буль - дивно це

2023-01-21 19:52 UTC, Eastvarga commented on models/contacts.js
> +  Object.assign(parsedData[contactIndex], body);
Забагато дій - чому не скористаєтесь методом масиву map?
при співпадінні item.id === contactId просто повертати не поточний елемент а { ...item, ...body}
спробуйте, неписати зайвого коду, та вчіться застосовувати методи масивів коректно мінімізуючи строки коду
 map((elem,index, array)=>{}) сам індекс співпадіння теж можна витягти із мапінгу масиву

2023-01-21 19:52 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(200).json({ message: "success", contact });
res.status(200).json(contact ); цього достатньо - поле message зайве

2023-01-21 19:52 UTC, Eastvarga commented on routes/api/contacts.js
> +      res.status(400).json({ message: "missing required name field" });
Ви не розумієте призначення валідації - Ваш код не дійде до цьго якщо Ви вірно створили валідацію - ця логіка відноситься до валідації. Треба виправити

2023-01-21 19:52 UTC, Eastvarga commented on routes/api/contacts.js
> +    const isContactDeleted = await removeContact(contactId);
Вище написав - не повинні так себе вести функції одного рівня призначення - повертати або ниічого або видалений контакт, треба виправити

2023-01-21 19:52 UTC, Eastvarga commented on routes/api/contacts.js
> +    if (Object.keys(req.body).length === 0) {
Знову, валідація навіщо була в такому разі (contactValidation) ??

2023-01-21 19:52 UTC, Eastvarga commented on server.js
>  app.listen(3000, () => {
const PORT = process.env.PORT||3000 - де загубили?
не вміння та не знання цих осново - погано, дуже погано для Вас

2023-01-22 12:04 UTC, Natali2721 commented on server.js
>  app.listen(3000, () => {
Дякую. "Понял, осознал, больше не повторится"

2023-01-22 12:04 UTC, Natali2721 commented on routes/api/contacts.js
> +    if (Object.keys(req.body).length === 0) {
пофіксила

2023-01-22 12:06 UTC, Natali2721 commented on routes/api/contacts.js
> +      res.status(400).json({ message: "missing required name field" });
пофіксила, дякую

2023-01-22 12:06 UTC, Natali2721 commented on routes/api/contacts.js
> +    res.status(200).json({ message: "success", contact });
пофіксила, дякую

2023-01-22 12:06 UTC, Natali2721 commented on models/contacts.js
> +  Object.assign(parsedData[contactIndex], body);
прийнято

2023-01-22 12:07 UTC, Natali2721 commented on models/contacts.js
> +    return false;
дякую

2023-01-22 12:08 UTC, Natali2721 commented on models/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(dataAfterRemove));
виконано

2023-01-22 12:08 UTC, Natali2721 commented on models/contacts.js
> +  return JSON.parse(data);
перевикористання застосувала, дякую

2023-01-22 12:09 UTC, Natali2721 commented on models/contacts.js
> +  if (dataAfterRemove.length === parsedData.length) {
дякую

2023-01-22 12:13 UTC, Natali2721 commented on server.js
>  app.listen(3000, () => {
Виправила на мій погляд все, але є проблема з PUT. В упор не бачу де. GET, DELETE, POST працюють, а PUT через постман не хоче. {"error":"contactId is not defined"}. Please help

2023-01-22 13:11 UTC, Natali2721 commented on server.js
>  app.listen(3000, () => {
Sorry, Put пофіксила

2023-01-23 19:14 UTC, Eastvarga approved these changes
Є коментар

2023-01-23 19:14 UTC, Eastvarga commented on schemas/validation.js
> +    });
додавання .min(1) вирішує питання з валідацією коли відсутні усі опціональні поля.

2023-01-23 19:15 UTC, merged