Hw03 mongodb
Natali2721/nodejs-homework-rest-api pull request #2
Opened 2023-01-27 13:38 UTC by Natali2721

Вітаю, прошу перевірити мій код. Шукаю шляхи вдосконалення. Прошу поради, чи треба логіку роботи з БД з контроллерів переносити в окремі сервіси та на якому етапі валідувати запит Joi : в контролері чи в роутах? Соррі, якщо питання дивні. Дякую

2023-01-27 20:19 UTC, Eastvarga requested changes
Добре, однак дещо треба доопрацювати

2023-01-27 20:19 UTC, Eastvarga commented on controllers/contacts/addContact.js
> +  }
Ця частина відноситься до валідації її треба винесту на рівень мідлварів де у Вас вже є валідація айді запитів

2023-01-27 20:19 UTC, Eastvarga commented on controllers/contacts/getContactById.js
> +  res.status(200).json({ contact });
res.status(200).json(contact );  достатньо повертати сам об'єкт контакту, не у полі

2023-01-27 20:19 UTC, Eastvarga commented on controllers/contacts/updateContactById.js
> +  const { error } = putContactsSchema.validate(req.body);
теж саме по валідації тіла запиту

2023-01-27 20:19 UTC, Eastvarga commented on controllers/contacts/updateFavorite.js
> +  const { error } = updateFavoriteSchema.validate(req.body);
теж саме, валідацію винести з контроллера

2023-01-27 20:19 UTC, Eastvarga commented on helpers/isValidId.js
> +const isValidId = (req, res, next) => {
створіть подібні мідлвари ще для валідацій тіла запитів та використайте їх у раутах

2023-01-27 20:19 UTC, Eastvarga commented on routes/api/contacts.js
> +  isValidId,
Ось це добре що помітили, мало хто це зробив

2023-01-27 20:19 UTC, Eastvarga commented on routes/api/contacts.js
> +router.post("/", controllerWrapper(controller.addContact));
router.post("/", **validateContactDto**, controllerWrapper(controller.addContact)); валідацію тіла запиту додайте приблизно так

2023-01-27 20:19 UTC, Eastvarga commented on routes/api/contacts.js
> +);
router.put(
  "/:contactId",
  isValidId, - validateIdParam краще бо isValidId не повертає ж буль
**validateUpdateContactDto**,  - теж додайте мідлвар валідації
  controllerWrapper(controller.updateContactById)
);

2023-01-27 20:19 UTC, Eastvarga commented on server.js
> +const { DB_HOST, PORT = 3000 } = process.env;
добре, однак, краще створити конфігураційний файл та з нього імпортувати  змінні конфігурації серверу

2023-01-28 10:52 UTC, Natali2721 commented on controllers/contacts/addContact.js
> +  }
done

2023-01-28 10:56 UTC, Natali2721 commented on controllers/contacts/getContactById.js
> +  res.status(200).json({ contact });
done

2023-01-28 10:57 UTC, Natali2721 commented on controllers/contacts/updateContactById.js
> +  const { error } = putContactsSchema.validate(req.body);
done

2023-01-28 10:57 UTC, Natali2721 commented on controllers/contacts/updateFavorite.js
> +  const { error } = updateFavoriteSchema.validate(req.body);
done

2023-01-28 10:58 UTC, Natali2721 commented on helpers/isValidId.js
> +const isValidId = (req, res, next) => {
done

2023-01-28 10:58 UTC, Natali2721 commented on routes/api/contacts.js
> +  isValidId,
thanks

2023-01-28 10:58 UTC, Natali2721 commented on routes/api/contacts.js
> +router.post("/", controllerWrapper(controller.addContact));
done

2023-01-28 11:01 UTC, Natali2721 commented on routes/api/contacts.js
> +);
done

2023-01-28 11:04 UTC, Natali2721 commented on server.js
> +const { DB_HOST, PORT = 3000 } = process.env;
наразі перебуваю в процесі вивчення побудови структури проекту, бачу, що є дуже багато можливостей і спробую, як точно це осягну, дякую

2023-01-28 17:34 UTC, Eastvarga approved these changes

2023-01-28 17:34 UTC, Eastvarga commented on controllers/contacts/addContact.js
> +  res.status(201).json({ code: 201, result });
res.status(201).json(result ); такого запису достатньо

2023-01-28 17:34 UTC, merged

2023-02-02 11:12 UTC, Natali2721 commented on controllers/contacts/addContact.js
> +  res.status(201).json({ code: 201, result });
done